apiVersion: v1
kind: Service
metadata:
  labels:
    app: integracion-hra-api
    tier: backend
  name: integracion-hra-api-service
  namespace: cl-dssa-api
spec:
  type: NodePort
  selector:
    app: integracion-hra-api
    tier: backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80